rm(list = ls())
gc()
library(stringr)
library(clusterProfiler)
library(org.Hs.eg.db)
library(tidyverse)
library(openxlsx)
setwd('F:/my projects/02.论文/论文四_桥本甲状腺炎/Project/Datas/Intersctomes/')
circbank <- read.delim('09.circbank/circbank_miRNA_all_v1.txt')
sum(rowSums(is.na(circbank)))
sum(duplicated(paste0(circbank$miR_ID,circbank$circbase_ID)))
circbank <- circbank[,c(1,2)]
colnames(circbank) <- c('Gene1','Gene2')
sum(duplicated(paste0(circbank$Gene1,circbank$Gene2)))
sum(!duplicated(c(circbank$Gene1,circbank$Gene2)))
sum(str_detect(circbank$Gene1,'hsa-mir'))
sum(str_detect(circbank$Gene2,'hsa-mir'))
write.table(circbank,'12.ALL/09.circBank.txt',row.names = F,quote = F)
