rm(list = ls())
gc()
library(stringr)
library(clusterProfiler)
library(org.Hs.eg.db)
library(tidyverse)
library(openxlsx)
setwd('F:/my projects/02.论文/论文四_桥本甲状腺炎/Project/Datas/Intersctomes/12.ALL/')
files <- list.files()
# Intersect1 <- read.table(files[1],header = T)
# Intersect2 <- read.delim(files[2],header = T)
# Intersect3 <- read.table(files[3],header = T)
# Intersect4 <- read.table(files[4],header = T)
# Intersect5 <- read.delim(files[5],header = T)
# Intersect6 <- read.table(files[6],header = T)
# Intersect7 <- read.delim(files[7],header = T)
# Intersect8 <- read.table(files[8],header = T)
# Intersect9 <- read.table(files[9],header = T)
# Intersect10 <- read.delim(files[10],header = T)
# Intersect11 <- read.table(files[11],header = T)
# Intersect <- rbind(Intersect1,Intersect2,Intersect3,Intersect4,Intersect5
#       ,Intersect6,Intersect7,Intersect8,Intersect9,Intersect10
#       ,Intersect1)
# write.table(Intersect,'../12.ALL/Interactome.txt',row.names = F,quote = F,sep='\t')
Intersect <- read.delim('Interactome.txt')
sum(str_detect(Intersect$Gene1,'hsa-mir'))
sum(str_detect(Intersect$Gene2,'hsa-mir'))
Intersect$Gene1[str_detect(Intersect$Gene1,'hsa-mir')] <- sub(pattern = 'hsa-mir',replacement = 'hsa-miR',Intersect$Gene1[str_detect(Intersect$Gene1,'hsa-mir')])
Intersect$Gene2[str_detect(Intersect$Gene2,'hsa-mir')] <- sub(pattern = 'hsa-mir',replacement = 'hsa-miR',Intersect$Gene2[str_detect(Intersect$Gene2,'hsa-mir')])
sum(duplicated(paste0(Intersect$Gene1,Intersect$Gene2)))
Intersect <- Intersect[!duplicated(paste0(Intersect$Gene1,Intersect$Gene2)),]
sum(!duplicated(c(Intersect$Gene1,Intersect$Gene2)))
write.table(Intersect,'../12.ALL/Interactome.txt',row.names = F,quote = F,sep='\t')
